# Generated by Django 2.2.4 on 2020-02-05 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20200204_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_vendors', to=settings.AUTH_USER_MODEL),
        ),
    ]
