# Generated by Django 3.0.3 on 2020-02-29 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0007_auto_20200204_2208'),
        ('purchases', '0004_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Header Purchase', 'verbose_name_plural': 'Header Purchases'},
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='proveedor',
            new_name='vendor',
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_purchasedetails', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_purchasedetails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detail Purchase',
                'verbose_name_plural': 'Detail Purchases',
            },
        ),
    ]
