# Generated by Django 2.2.4 on 2019-09-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='state',
            new_name='status',
        ),
    ]
